# 載入所需套件

In [1]:
import requests
import pandas as pd
import json
from datetime import datetime
import os
import time

# 定義爬取個股交易量函數

In [2]:
def volume_crawler(year,month,stock_id):
    date=datetime(year,month,1).strftime('%Y%m%d')
    url='http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date={}&stockNo={}&'.format(date,stock_id)
    response=requests.get(url)
    s=json.loads(response.text)
    df=pd.DataFrame(s['data'],columns=s['fields'])
    
    return df

# 爬取指定月份個股交易量資料

In [3]:
volume_crawler(2017,5,2330)

,日期,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,106/05/02,"45,851,963","9,053,856,108",198.50,199.00,195.50,196.50,+2.00,"15,718"
1,106/05/03,"27,240,962","5,390,698,304",198.00,198.50,197.00,198.00,+1.50,"9,259"
2,106/05/04,"22,194,084","4,394,409,518",198.50,199.00,197.00,198.00,0.00,"8,787"
3,106/05/05,"17,618,358","3,484,019,026",197.00,198.50,197.00,197.50,-0.50,"6,078"
4,106/05/08,"39,591,009","7,943,498,809",199.00,202.50,199.00,202.50,+5.00,"15,190"
5,106/05/09,"48,285,324","9,920,879,512",205.50,207.00,203.50,203.50,+1.00,"15,467"
6,106/05/10,"31,075,759","6,369,713,620",204.00,206.00,204.00,205.50,+2.00,"11,094"
7,106/05/11,"44,286,097","9,144,772,197",204.50,208.50,204.00,207.50,+2.00,"16,478"
8,106/05/12,"25,507,045","5,246,098,865",205.00,207.00,205.00,206.00,-1.50,"7,515"
9,106/05/15,"25,922,334","5,324,070,590",204.00,206.00,204.00,206.00,0.00,"8,141"
10,106/05/16,"36,604,672","7,468,111,624",205.00,205.00,203.50,204.50,-1.50,"11,066"
11,106/05/17,"22,606,380","4,599,735,640",203.00,204.00,203.00,204.00,-0.50,"9,323"
12,106/05/18,"22,490,217","4,559,780,051",202.50,204.00,201.50,203.50,-0.50,"6,983"
13,106/05/19,"17,163,108","3,490,280,961",203.50,204.50,202.50,203.00,-0.50,"6,014"
14,106/05/22,"17,419,705","3,554,245,920",203.50,205.00,203.00,205.00,+2.00,"5,278"
15,106/05/23,"23,028,298","4,738,103,907",205.00,207.00,204.50,205.00,0.00,"7,003"
16,106/05/24,"18,307,715","3,760,309,975",205.00,206.00,205.00,205.50,+0.50,"5,141"
17,106/05/25,"26,088,748","5,388,004,408",206.00,207.00,205.50,207.00,+1.50,"7,406"
18,106/05/26,"32,976,727","6,794,923,568",205.00,207.00,205.00,207.00,0.00,"8,059"
19,106/05/31,"67,935,145","13,853,122,715",206.50,207.00,203.00,203.00,-4.00,"11,757"

# 爬取指定時間範圍個股交易量資料

In [4]:
stock_ids=[2303,2330]
years=range(2016,2017)
months=range(1,13)

for stock_id in stock_ids:
    print('{}:'.format(stock_id))
    for year in years:
        print('{}年'.format(year))
        directory='每月個股成交量資料/{}/{}年'.format(stock_id,year)
        if not os.path.isdir(directory):
            os.makedirs(directory)
        for month in months:            
            if not os.path.exists(directory+'/{}月.xlsx'.format(month)):
                df=volume_crawler(year,month,stock_id)
                df.to_excel(directory+'/{}月.xlsx'.format(month),index=False)
                print('{}月'.format(month))
                time.sleep(5)

2303:
2016年
1月
2月
3月
4月
5月
6月
7月
8月
9月
10月
11月
12月
2330:
2016年
1月
2月
3月
4月
5月
6月
7月
8月
9月
10月
11月
12月